
# version: "3.8"

services:
  postgres_database_1:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=Postgres_Password_3000
      - POSTGRES_USER=Postgres_User

    ports:
      - "3000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sqlserver_database_1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SQL_Server_Password_1000
    ports:
      - "1000:1433"
    # command: 
    #   - /bin/bash -c "for f in /source/init_script/SQL_Server_1/*.sql; do /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -i $f; `SQL Server - Init completed`"

    volumes:
      - sqlserver_data1:/var/opt/mssql/data

  sqlserver_database_2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SQL_Server_Password_2000
    ports:
      - "2000:1433"
    volumes:
      - sqlserver_data2:/var/opt/mssql/data
      

volumes:
  postgres_data:  # Optional
  sqlserver_data1:  # Optional for SQL Server
  sqlserver_data2:  # Optional for MariaDB
